# 指定使用的模组元数据格式版本（固定）
modLoader = "javafml"
loaderVersion = "[4,)"  # 支持的加载器版本范围

# 你的 Mod 信息
[[mods]]
modId = "${mod_id}"               # 引用 gradle.properties 中的 mod_id
version = "${mod_version}"        # 引用 gradle.properties 中的 mod_version
displayName = "${mod_name}"       # 引用 gradle.properties 中的 mod_name # 可选
logoFile = "guamod.png"           # 可选，放在 assets/guamod/textures/ 下？实际应放在 META-INF 同级？通常 logoFile 放在 META-INF 文件夹内或根资源目录
credits = "感谢名单"
authors = "yxm"
description = '''
- 添加了新的剑、配方
- 通过进度解锁
- 14班专用
'''

# 依赖配置（如果有）
[[dependencies.guamod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.guamod]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"